services:
  application:
    build: .
    container_name: intern-student-service
    ports:
      - "8098:8098"
    depends_on:
      - mysqldb
    networks:
      - springboot-db-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/studentdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    volumes:
      - ./upload:/upload
      - /data/springboot-app

  mysqldb:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: studentdb
    volumes:
      - /data/mysql
    networks:
      - springboot-db-net

networks:
  springboot-db-net:
    driver: bridge
